### ISSUE TITLE
Mouse Input Lag Goes Up to 100+ ms When Using a Mouse w/ Software

### ISSUE THREAD

**Issue by MRH4DES** [ppy/osu-wine#5]
Tested with Razer Deathadder Chroma, Logitech G502, and Logitech G700s (both wireless and wired).

**Comment by peppy** [comment]
Just wondering if you found a solution to this issue?

**Comment by MRH4DES** [comment]
High polling rates were the issue. Anything under 500 reports/second did not significantly affect gameplay. Polling rates can be reduced manually through the mouse software.
